### ISSUE TITLE
Realidad Aumentada_Prototipo

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-vo#1]
[RA_T1_PROTOTIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-vo/files/14315332/RA_T1_PROTOTIPO.pdf)

**Comment by NoeliaGlez** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
